[tool.towncrier]
name = "Fullstack Template"
directory = "changes"
filename = "CHANGELOG.md"
start_string = "<!-- towncrier release notes start -->\n"
title_format = "## [{version}]"
ignore = ["README.md"]

[[tool.towncrier.type]]
name = "Added"

[[tool.towncrier.type]]
name = "Changed"

[[tool.towncrier.type]]
name = "Fixed"

[[tool.towncrier.type]]
name = "Removed"

[[tool.towncrier.type]]
name = "Security"

[[tool.towncrier.type]]
name = "Maintenance"
